 platform :ios, '9.0'

target 'ChatApp' do
    use_frameworks!

  # Pods for ChatApp
    pod 'Firebase/Core'
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'SVProgressHUD', '2.2.1'
    pod 'ChameleonFramework'


end
